// <auto-generated />
namespace ShopOnlineMvc1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ad2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ad2));
        
        string IMigrationMetadata.Id
        {
            get { return "201806160956480_ad2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
